config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :menu_items

  get '/menu_item/submit_order', to: 'menu_items#submit_order'
  get '/menu_item/confirm_order', to: 'menu_items#confirm_order'
  post '/menu_item/finalize_order', to: 'menu_items#finalize_order'
  get '/menu_item/tip', to: 'menu_items#tip'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  enum category: %i[appetizer main_course side dessert]
  has_many :order_items
  has_many :orders, through: :order_items
  validates :price, numericality: { greater_than: 0}
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_many :menu_items, through: :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :menu_item
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create edit update destroy]

  # GET /menu_items
  # GET /menu_items.json
  def index
    @menu_items = MenuItem.all
  end

  def submit_order
    @menu_items = MenuItem.all
  end

  def confirm_order
    @sum = 0
    @menu_vals = params.permit(params.keys).to_h.select { |key, _value| key.to_i.to_s == key }
    @menu_vals.each do |key, val|
      @sum += ((BigDecimal.new(MenuItem.find(key.to_i).price, 4) * val.to_f).to_f* 100).round / 100.0
    end
  end

  def tip
    @sum = 0
    @menu_vals = params[:order].permit(params[:order].keys).to_h.select { |key, _value| key.to_i.to_s == key }
    @menu_vals.each do |key, val|
      @sum += (BigDecimal.new(MenuItem.find(key.to_i).price, 4) * val.to_f).to_f
    end
    @sum = ((@sum * (1 + BigDecimal.new(params[:tip]))).to_f * 100).round / 100.0
    @tip = params[:tip]
  end

  def finalize_order
    @order = Order.new

    params[:order].permit(params[:order].keys).to_h.each do |key, _val|
      @order.menu_items << MenuItem.find(key.to_i)
    end
    @order.tip = params[:tip]
    if @order.save
      params[:order].permit(params[:order].keys).to_h.each do |key, val|
        OrderItem.find_by(menu_item_id: key.to_i).update!(number: val.to_i)
      end
      @menu_items = MenuItem.all
      render :submit_order, notice: 'Order successfully created.'
    else
      @menu_items = MenuItem.all
      render :submit_order, notice: 'Order not created, error.'
    end
  end

  # GET /menu_items/1
  # GET /menu_items/1.json
  def show; end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end

  # GET /menu_items/1/edit
  def edit; end

  # POST /menu_items
  # POST /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully created.' }
        format.json { render :show, status: :created, location: @menu_item }
      else
        format.html { render :new }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1
  # PATCH/PUT /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1
  # DELETE /menu_items/1.json
  def destroy
    @menu_item.destroy
    respond_to do |format|
      format.html { redirect_to menu_items_url, notice: 'Menu item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_menu_item
    @menu_item = MenuItem.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def menu_item_params
    params.require(:menu_item).permit(:name, :description, :price, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MenuApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menu_items/_form.html.erb
<%= form_for(menu_item) do |f| %>
  <% if menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
      <% menu_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price, step: 0.01 %>
  </div>

  <div class="field">
  <%= f.label :category %><br>
  <%= f.select :category, MenuItem.categories.keys %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menu_items/_table.html.erb
<h2><%= title %></h2>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% (@menu_items.select { |item| item.category==category}).each do |menu_item| %>
        <tr>
          <td><%= menu_item.name %></td>
          <td><%= menu_item.description %></td>
          <td><%= menu_item.price %></td>
          <td><%= label_tag :selection %>
          <%= number_field_tag menu_item.id, 0, min: 0 %></td>
          <td><%= link_to 'Show', menu_item, {class: "btn btn-default"} %></td>
          <td><%= link_to 'Edit', edit_menu_item_path(menu_item), {class: "btn btn-default"} %></td>
          <td><%= link_to('Destroy', menu_item, {method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-default"}) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/menu_items/confirm_order.html.erb
<p>Your order costs <%= @sum %></p>

<%= button_to "Confirm", action: "finalize_order", params: {order: @menu_vals, tip: 0} %>
<div>
  <%= link_to "tip: 10%", action: "tip", params: {order: @menu_vals, tip: 0.1} %>
  <%= link_to "tip: 15%", action: "tip", params: {order: @menu_vals, tip: 0.15} %>
  <%= link_to "tip: 20%", action: "tip", params: {order: @menu_vals, tip: 0.2} %>
</div>
<%= link_to 'Back', menu_item_submit_order_path %>

app/views/menu_items/edit.html.erb
<h1>Editing Menu Item</h1>

<%= render 'form', menu_item: @menu_item %>

<%= link_to 'Show', @menu_item %> |
<%= link_to 'Back', menu_items_path %>

app/views/menu_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menu Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu_items.each do |menu_item| %>
      <tr>
        <td><%= menu_item.name %></td>
        <td><%= menu_item.description %></td>
        <td><%= menu_item.price %></td>
        <td><%= menu_item.category %></td>
        <td><%= link_to 'Show', menu_item %></td>
        <td><%= link_to 'Edit', edit_menu_item_path(menu_item) %></td>
        <td><%= link_to 'Destroy', menu_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu Item', new_menu_item_path %>

app/views/menu_items/new.html.erb
<h1>New Menu Item</h1>

<%= render 'form', menu_item: @menu_item %>

<%= link_to 'Back', menu_items_path %>

app/views/menu_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @menu_item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menu_item.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @menu_item.category %>
</p>

<%= link_to 'Edit', edit_menu_item_path(@menu_item) %> |
<%= link_to 'Back', menu_items_path %>

app/views/menu_items/submit_order.html.erb
<p id="notice"><%= notice %></p>

<h1>Menu</h1>

<%= form_tag(menu_item_confirm_order_path, method: :get) do %>
  <%= render 'table', menu_item: @menu_items, title: "Appetizer", category: "appetizer" %>

  <br>

  <%= render 'table', menu_item: @menu_items, title: "Entrees", category: "main_course" %>

  <br>

  <%= render 'table', menu_item: @menu_items, title: "Dessert", category: "dessert" %>

  <br>

  <%= render 'table', menu_item: @menu_items, title: "Sides", category: "side" %>
  <%= submit_tag("Submit") %>
<%end%>
<br>

app/views/menu_items/tip.html.erb
<p>Your order costs <%= @sum %></p>

<%= button_to "Confirm", action: "finalize_order", params: {order: @menu_vals, tip: @tip} %>
<%= link_to 'Back', menu_item_confirm_order_path %>